### ISSUE TITLE
Improve readability and insertion performance

### ISSUE THREAD

**Issue by tomtiao** [YouMoeYi/bilibili-hd-avatar-inspect-script#1]
We can make use of JavaScript syntax to make the code easier to read.

https://github.com/YouMoeYi/bilibili-hd-avatar-inspect-script/blob/58949d3a464e533ca00366fec828a4c6e7cd28d2/bilibili%20hd%20avatar%20inspect%20script.js#L32-L40

```
function isTrueObject(any) {
        return Object.prototype.toString.call(any) == '[object Object]';
    }
```

https://github.com/YouMoeYi/bilibili-hd-avatar-inspect-script/blob/58949d3a464e533ca00366fec828a4c6e7cd28d2/bilibili%20hd%20avatar%20inspect%20script.js#L42-L53

```
function isEmptyObject(obj) {
        return isTrueObject(obj) ?
            (Object.keys(obj).length) == 0 :
            false;
    }
```

https://github.com/YouMoeYi/bilibili-hd-avatar-inspect-script/blob/58949d3a464e533ca00366fec828a4c6e7cd28d2/bilibili%20hd%20avatar%20inspect%20script.js#L61-L70

```
function css(element, config) {
        if (isTrueObject(config) && !isEmptyObject(config)) {
            for (let [key, value] of Object.entries(config)) {
                element.style[key] = value
            }
        } else {
            alterThenThrow('css函数参数错误')
        }
    }
```

https://github.com/YouMoeYi/bilibili-hd-avatar-inspect-script/blob/58949d3a464e533ca00366fec828a4c6e7cd28d2/bilibili%20hd%20avatar%20inspect%20script.js#L86-L88

By listening to the load event raised by `<img id="h-avatar">`, we can speed up insertion on slow networks.

```
    // 正式运行脚本
    function work() {
        // 获取相应的DOM节点
        // ...
    }
    document.body.addEventListener('load', e => {
        if (e.target.id == 'h-avatar') {
            work()
        }
    }, true)
```

**Comment by UndefinedVoidNull** [comment]
**Thanks a lot for your issue and pull request!**
I have changed the script based on your pull request, but replace == with === and remove the semicolon to maintain the consistency of code style.

**Comment by tomtiao** [comment]
I suddenly realize that `return isTrueObject(obj) ?  (Object.keys(obj).length) == 0 : false;` is just `return isTrueObject(obj) && (Object.keys(obj).length === 0)`. 🥺

**Comment by UndefinedVoidNull** [comment]
That's it.
`&&` operator can be used in conditional judgement, but the former one seems easier to understand.

**Comment by UndefinedVoidNull** [comment]
> We can make use of JavaScript syntax to make the code more easier to read.

🤣 单音节词比较级后加er就可了，多音节词比较级才是前加more
easier ✅ 
much easier ✅ 
more easier ❌
much more easier ❌

importanter ❌
much importanter ❌
more important ✅
much more important ✅

much 做程度副词表强调，常加在比较级前。
别问为啥这么敏感，问就是高考英语短文改错后遗症。😅
