### ISSUE TITLE
脚本失效,无法显示头像按钮

### ISSUE THREAD

**Issue by lolisix** [YouMoeYi/bilibili-hd-avatar-inspect-script#3]
脚本失效,无法显示头像按钮
<a href="https://sm.ms/image/OrGQZqCiewHtTDI" target="_blank"><img src="https://s2.loli.net/2021/12/13/OrGQZqCiewHtTDI.png" ></a>
<a href="https://sm.ms/image/7OhqmvYiVzZawR2" target="_blank"><img src="https://s2.loli.net/2021/12/13/7OhqmvYiVzZawR2.png" ></a>

**Comment by UndefinedVoidNull** [comment]
确实 我自己也发现了 过几天修复一下

**Comment by UndefinedVoidNull** [comment]
更新一下应该可以了
